server:
   port: 9191

spring:
    application:
           name:  userservice
    datasource:
         url: jdbc:mysql://localhost:3306/hotelmanagement
         username: root
         password: myadmin
    jpa:
       hibernate:
             ddl-auto: update
       show-sql: true
